version: "3.2"
services: 
  db:
    image: mysql
    container_name: mysql-container-test4
    volumes: 
      - /var/lib/mysql:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
  api:
    build: "./api"
    container_name: node-container-test4 
    volumes: 
      - ./api:/home/node/app
    ports: 
      - "9001:9001"
    depends_on: 
      - db
    restart: always
  web:
    image: "php:7.2-apache"
    container_name: php-container-test4
    volumes: 
      - ./website:/var/www/html
    ports: 
      - "8880:80"
    restart: always
    depends_on: 
      - api